<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Producto;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $productos = [
            ['nombre' => 'Playera Roja', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una playera de color rojo', 
            'precio' => 150.00,'cantidad' => 10, 'categoria_id' => 1, 'propietario_id' => 1],
            ['nombre' => 'Pantalón Azul', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un pantalón de color azul', 
            'precio' => 250.00,'cantidad' => 5, 'categoria_id' => 2, 'propietario_id' => 2],
            ['nombre' => 'Vestido Floral', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un vestido con estampado floral', 
            'precio' => 100.00,'cantidad' => 8, 'categoria_id' => 3, 'propietario_id' => 3],
            ['nombre' => 'Camisa Blanca', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una camisa de color blanco', 
            'precio' => 157.00,'cantidad' => 7, 'categoria_id' => 4, 'propietario_id' => 4],
            ['nombre' => 'Traje Negro', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un traje elegante de color negro', 
            'precio' => 180.00,'cantidad' => 6, 'categoria_id' => 5, 'propietario_id' => 5],
            ['nombre' => 'Playera Negra', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una playera de color negro', 
            'precio' => 170.00,'cantidad' => 12, 'categoria_id' => 1, 'propietario_id' => 2],
            ['nombre' => 'Pantalón Gris', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un pantalón de color gris', 
            'precio' => 120.00,'cantidad' => 4, 'categoria_id' => 2, 'propietario_id' => 1],
            ['nombre' => 'Vestido Rojo', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un vestido de color rojo', 
            'precio' => 150.00,'cantidad' => 9, 'categoria_id' => 3, 'propietario_id' => 3],
            ['nombre' => 'Camisa Azul', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una camisa de color azul', 
            'precio' => 250.00,'cantidad' => 6, 'categoria_id' => 4, 'propietario_id' => 1],
            ['nombre' => 'Traje Gris', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un traje elegante de color gris', 
            'precio' => 350.00,'cantidad' => 7, 'categoria_id' => 5, 'propietario_id' => 4],        
            ['nombre' => 'Playera Verde', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una playera de color verde', 
            'precio' => 250.00,'cantidad' => 8, 'categoria_id' => 1, 'propietario_id' => 5],
            ['nombre' => 'Pantalón Negro', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un pantalón de color negro', 
            'precio' => 170.00,'cantidad' => 5, 'categoria_id' => 2, 'propietario_id' => 4],
            ['nombre' => 'Vestido Azul', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un vestido de color azul', 
            'precio' => 150.00,'cantidad' => 7, 'categoria_id' => 3, 'propietario_id' => 2],
            ['nombre' => 'Camisa Rosa', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una camisa de color rosa', 
            'precio' => 150.00,'cantidad' => 6, 'categoria_id' => 4, 'propietario_id' => 1],
            ['nombre' => 'Traje Azul Marino', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un traje elegante de color azul marino', 
            'precio' => 150.00,'cantidad' => 5, 'categoria_id' => 5, 'propietario_id' => 5],
            ['nombre' => 'Playera Blanca', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una playera de color blanco', 
            'precio' => 150.00,'cantidad' => 10, 'categoria_id' => 1, 'propietario_id' => 3],
            ['nombre' => 'Pantalón Café', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un pantalón de color café', 
            'precio' => 130.00,'cantidad' => 4, 'categoria_id' => 2, 'propietario_id' => 1],
            ['nombre' => 'Vestido Negro', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un vestido de color negro', 
            'precio' => 170.00,'cantidad' => 8, 'categoria_id' => 3, 'propietario_id' => 2],
            ['nombre' => 'Camisa Verde', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una camisa de color verde', 
            'precio' => 150.00,'cantidad' => 5, 'categoria_id' => 4, 'propietario_id' => 4],
            ['nombre' => 'Traje Beige', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un traje elegante de color beige', 
            'precio' => 420.00,'cantidad' => 6, 'categoria_id' => 5, 'propietario_id' => 5],
            ['nombre' => 'Playera Amarilla', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una playera de color amarillo', 
            'precio' => 140.00,'cantidad' => 9, 'categoria_id' => 1, 'propietario_id' => 5],
            ['nombre' => 'Pantalón Blanco', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un pantalón de color blanco', 
            'precio' => 160.00,'cantidad' => 6, 'categoria_id' => 2, 'propietario_id' => 4],
            ['nombre' => 'Vestido Morado', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un vestido de color morado', 
            'precio' => 156.00,'cantidad' => 7, 'categoria_id' => 3, 'propietario_id' => 3],
            ['nombre' => 'Camisa Negra', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una camisa de color negro', 
            'precio' => 153.00,'cantidad' => 8, 'categoria_id' => 4, 'propietario_id' => 2],
            ['nombre' => 'Traje Marrón', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un traje elegante de color marrón', 
            'precio' => 240.00,'cantidad' => 5, 'categoria_id' => 5, 'propietario_id' => 5],
            ['nombre' => 'Playera Naranja', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una playera de color naranja', 
            'precio' => 530.00,'cantidad' => 8, 'categoria_id' => 1, 'propietario_id' => 1],
            ['nombre' => 'Pantalón Azul Marino', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un pantalón de color azul marino', 
            'precio' => 230.00,'cantidad' => 6, 'categoria_id' => 2, 'propietario_id' => 2],
            ['nombre' => 'Vestido Verde', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un vestido de color verde', 
            'precio' => 143.00,'cantidad' => 9, 'categoria_id' => 3, 'propietario_id' => 4],
            ['nombre' => 'Camisa Gris', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una camisa de color gris', 
            'precio' => 150.00,'cantidad' => 7, 'categoria_id' => 4, 'propietario_id' => 1],
            ['nombre' => 'Traje Negro Formal', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un traje formal de color negro', 
            'precio' => 134.00,'cantidad' => 6, 'categoria_id' => 5, 'propietario_id' => 3],
            ['nombre' => 'Playera Rosa', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una playera de color rosa', 
            'precio' => 150.00,'cantidad' => 9, 'categoria_id' => 1, 'propietario_id' => 2],
            ['nombre' => 'Pantalón Rojo', 'estado' => 'consignado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un pantalón de color rojo', 
            'precio' => 150.00,'cantidad' => 7, 'categoria_id' => 2, 'propietario_id' => 1],
            
            ['nombre' => 'Vestido Azul Claro',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un vestido de color azul claro', 
            'precio' => 153.00,'cantidad' => 8, 'categoria_id' => 3, 'propietario_id' => 3],
            ['nombre' => 'Camisa Amarilla',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una camisa de color amarillo', 
            'precio' => 132.00,'cantidad' => 6, 'categoria_id' => 4, 'propietario_id' => 3],
            ['nombre' => 'Traje Azul Claro',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un traje elegante de color azul claro', 
            'precio' => 124.00,'cantidad' => 5, 'categoria_id' => 5, 'propietario_id' => 5],
            ['nombre' => 'Playera Gris',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una playera de color gris', 
            'precio' => 121.00,'cantidad' => 10, 'categoria_id' => 1, 'propietario_id' => 4],
            ['nombre' => 'Pantalón Morado',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un pantalón de color morado', 
            'precio' => 125.00,'cantidad' => 5, 'categoria_id' => 2, 'propietario_id' => 5],
            ['nombre' => 'Vestido Blanco',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un vestido de color blanco', 
            'precio' => 120.00,'cantidad' => 9, 'categoria_id' => 3, 'propietario_id' => 1],
            ['nombre' => 'Camisa Naranja',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una camisa de color naranja', 
            'precio' => 160.00,'cantidad' => 7, 'categoria_id' => 4, 'propietario_id' => 2],
            ['nombre' => 'Traje Azul Oscuro',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un traje elegante de color azul oscuro', 
            'precio' => 180.00,'cantidad' => 6, 'categoria_id' => 5, 'propietario_id' => 4],
            ['nombre' => 'Playera Celeste',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una playera de color celeste', 
            'precio' => 150.00,'cantidad' => 8, 'categoria_id' => 1, 'propietario_id' => 1],
            ['nombre' => 'Pantalón Verde Oliva',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un pantalón de color verde oliva', 
            'precio' => 150.00,'cantidad' => 6, 'categoria_id' => 2, 'propietario_id' => 2],
            ['nombre' => 'Vestido Amarillo',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un vestido de color amarillo', 
            'precio' => 150.00,'cantidad' => 7, 'categoria_id' => 3, 'propietario_id' => 3],
            ['nombre' => 'Camisa Roja',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una camisa de color rojo', 
            'precio' => 145.00,'cantidad' => 6, 'categoria_id' => 4, 'propietario_id' => 4],
            ['nombre' => 'Traje Blanco',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un traje elegante de color blanco', 
            'precio' => 157.00,'cantidad' => 5, 'categoria_id' => 5, 'propietario_id' => 5],
            ['nombre' => 'Playera Azul Marino',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una playera de color azul marino', 
            'precio' => 321.00,'cantidad' => 9, 'categoria_id' => 1, 'propietario_id' => 4],
            ['nombre' => 'Pantalón Rosa',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un pantalón de color rosa', 
            'precio' => 241.00,'cantidad' => 5, 'categoria_id' => 2, 'propietario_id' => 5],
            ['nombre' => 'Vestido Naranja',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un vestido de color naranja', 
            'precio' => 163.00,'cantidad' => 8, 'categoria_id' => 3, 'propietario_id' => 5],
            ['nombre' => 'Camisa Azul Claro',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Una camisa de color azul claro', 
            'precio' => 142.00,'cantidad' => 7, 'categoria_id' => 4, 'propietario_id' => 4],
            ['nombre' => 'Traje Gris Oscuro',
            'fecha_publicacion' => '2024-05-04', 
            'descripcion' => 'Un traje elegante de color gris oscuro', 
            'precio' => 150.00,'cantidad' => 6, 'categoria_id' => 5, 'propietario_id' => 4]
        ];

        foreach ($productos as $producto) {
            $nuevo = new Producto();
            $nuevo->fill($producto);
            $nuevo->save();
        }
    }
}
